### PR TITLE
feat: allow to scan for custom iconify collections

### LINKED ISSUE #311: Allow extension of iconMatchRegex to support custom packages
I am having the same issue as https://github.com/nuxt/icon/issues/252.

This could be easily resolved if we were able to extend the `iconMatchRegex` variable. Then you just need to set `scan: true` and all the icons would be bundled with the client when `ssr: false`, without the hassle of having a custom iconify endpoint etc.

And since the app gets wrapped via capacitor and is installed on the users device anyways, I do not want to make any calls to some server to fetch icons.

I manually added my custom collection name (`cis`) in the installed module and built my app for capacitor (`ssr: false`) and it worked perfectly.

Important line from my package.lock
```json
{
    "dependencies": {
        ...
    },
    "devDependencies": {
        "@iconify-json/cis": "file:./assets/icon-sets/cis",
        "@iconify-json/wi": "^1.2.0",
        ....
    }
}

```

### PR DESCRIPTION
**Pull request by Quasarman**
### 🔗 Linked issue

Resolves #311 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This change allows users to overwrite the default `iconMatchRegex` used for scanning icons in the respective source files. It resolves the issue of custom iconify collections that are locally installed to be detected while creating the client side icon bundle.

### CODE REVIEW

**Comment by Quasarman** [comment]
@antfu FYI, let me know if this change is sufficient :)

**Comment by antfu** [comment]
I think we could go with similar approach as https://github.com/unocss/unocss/pull/4319

**Comment by Quasarman** [comment]
Thats an even nicer solution as it hides the regex logic!

**Review by antfu — APPROVED** [review]

**Comment by Pentadome** [comment]
Imo, it's not clear enough that we have to use `additionalCollections` to use custom collections. Especially because it's not mentioned in the readme.md. Would be nice if this could be updated <3

**Pull request merged**
